Client Is still messed up.
Client is currently getting some weird EOF error right off the bat.
  File "C:\...\client.py", line 45, in send_mode
    thing = input('Message: ')
EOFError: EOF when reading a line

couldn't find a a solution as of yet.